name: Feature Request
description: Suggest a new feature for WhenTo
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please check [Discussions](https://github.com/When-To/whento/discussions) first.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds?

  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      options:
        - Calendar management
        - Availability/scheduling
        - ICS/calendar sync
        - Authentication
        - Admin features
        - UI/UX
        - API
        - Other
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to submit a PR for this feature