// WhenTo - Collaborative event calendar for self-hosted environments
// Copyright (C) 2025 WhenTo Contributors
// SPDX-License-Identifier: BSL-1.1

package repository

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type UnifiedFeed struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ICSToken  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UnifiedFeedRepository struct {
	db *pgxpool.Pool
}

func NewUnifiedFeedRepository(db *pgxpool.Pool) *UnifiedFeedRepository {
	return &UnifiedFeedRepository{db: db}
}

// GetByUserID retrieves a user's unified feed and the included calendar IDs
func (r *UnifiedFeedRepository) GetByUserID(ctx context.Context, userID uuid.UUID) (*UnifiedFeed, []uuid.UUID, error) {
	query := `SELECT id, user_id, ics_token, created_at, updated_at FROM user_unified_feeds WHERE user_id = $1`

	var feed UnifiedFeed
	err := r.db.QueryRow(ctx, query, userID).Scan(
		&feed.ID, &feed.UserID, &feed.ICSToken, &feed.CreatedAt, &feed.UpdatedAt,
	)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to get unified feed: %w", err)
	}

	calendarIDs, err := r.getIncludedCalendarIDs(ctx, feed.ID)
	if err != nil {
		return nil, nil, err
	}

	return &feed, calendarIDs, nil
}

// Create creates a new unified feed for a user (token auto-generated by DB default)
func (r *UnifiedFeedRepository) Create(ctx context.Context, userID uuid.UUID) (*UnifiedFeed, error) {
	query := `
		INSERT INTO user_unified_feeds (user_id)
		VALUES ($1)
		RETURNING id, user_id, ics_token, created_at, updated_at
	`

	var feed UnifiedFeed
	err := r.db.QueryRow(ctx, query, userID).Scan(
		&feed.ID, &feed.UserID, &feed.ICSToken, &feed.CreatedAt, &feed.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create unified feed: %w", err)
	}

	return &feed, nil
}

// UpdateCalendars replaces the set of calendars included in a unified feed
func (r *UnifiedFeedRepository) UpdateCalendars(ctx context.Context, feedID uuid.UUID, calendarIDs []uuid.UUID) error {
	tx, err := r.db.Begin(ctx)
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	// Delete existing entries
	_, err = tx.Exec(ctx, `DELETE FROM unified_feed_calendars WHERE unified_feed_id = $1`, feedID)
	if err != nil {
		return fmt.Errorf("failed to clear calendar selections: %w", err)
	}

	// Insert new entries
	if len(calendarIDs) > 0 {
		batch := &pgx.Batch{}
		for _, calID := range calendarIDs {
			batch.Queue(
				`INSERT INTO unified_feed_calendars (unified_feed_id, calendar_id) VALUES ($1, $2) ON CONFLICT DO NOTHING`,
				feedID, calID,
			)
		}
		br := tx.SendBatch(ctx, batch)
		for range calendarIDs {
			if _, err := br.Exec(); err != nil {
				br.Close()
				return fmt.Errorf("failed to insert calendar selection: %w", err)
			}
		}
		br.Close()
	}

	// Update timestamp
	_, err = tx.Exec(ctx, `UPDATE user_unified_feeds SET updated_at = NOW() WHERE id = $1`, feedID)
	if err != nil {
		return fmt.Errorf("failed to update timestamp: %w", err)
	}

	return tx.Commit(ctx)
}

// RegenerateToken generates a new ICS token for a unified feed
func (r *UnifiedFeedRepository) RegenerateToken(ctx context.Context, feedID uuid.UUID) (string, error) {
	query := `
		UPDATE user_unified_feeds
		SET ics_token = encode(gen_random_bytes(32), 'hex'), updated_at = NOW()
		WHERE id = $1
		RETURNING ics_token
	`

	var token string
	err := r.db.QueryRow(ctx, query, feedID).Scan(&token)
	if err != nil {
		return "", fmt.Errorf("failed to regenerate token: %w", err)
	}

	return token, nil
}

// GetCalendarsForFeed retrieves all calendars included in a unified feed by its ICS token
func (r *UnifiedFeedRepository) GetCalendarsForFeed(ctx context.Context, icsToken string) ([]*Calendar, error) {
	query := `
		SELECT
			c.id,
			c.name,
			COALESCE(c.description, ''),
			c.threshold,
			c.allowed_weekdays,
			c.min_duration_hours,
			c.timezone,
			c.holidays_policy,
			c.allow_holiday_eves,
			c.owner_id,
			c.start_date,
			c.end_date,
			COUNT(p.id) as total_participants
		FROM user_unified_feeds uf
		JOIN unified_feed_calendars ufc ON ufc.unified_feed_id = uf.id
		JOIN calendars c ON c.id = ufc.calendar_id
		LEFT JOIN participants p ON p.calendar_id = c.id
		WHERE uf.ics_token = $1
		GROUP BY c.id, c.name, c.description, c.threshold, c.allowed_weekdays,
			c.min_duration_hours, c.timezone, c.holidays_policy, c.allow_holiday_eves,
			c.owner_id, c.start_date, c.end_date
	`

	rows, err := r.db.Query(ctx, query, icsToken)
	if err != nil {
		return nil, fmt.Errorf("failed to get calendars for feed: %w", err)
	}
	defer rows.Close()

	var calendars []*Calendar
	for rows.Next() {
		var cal Calendar
		err := rows.Scan(
			&cal.ID, &cal.Name, &cal.Description, &cal.Threshold,
			&cal.AllowedWeekdays, &cal.MinDurationHours, &cal.Timezone,
			&cal.HolidaysPolicy, &cal.AllowHolidayEves, &cal.OwnerID,
			&cal.StartDate, &cal.EndDate, &cal.TotalParticipants,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan calendar: %w", err)
		}
		calendars = append(calendars, &cal)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating calendars: %w", err)
	}

	return calendars, nil
}

// GetFeedOwnerInfo retrieves the display name, user ID, and timezone of the feed owner
func (r *UnifiedFeedRepository) GetFeedOwnerInfo(ctx context.Context, icsToken string) (string, uuid.UUID, string, error) {
	query := `
		SELECT u.display_name, u.id, u.timezone
		FROM user_unified_feeds uf
		JOIN users u ON u.id = uf.user_id
		WHERE uf.ics_token = $1
	`

	var displayName string
	var userID uuid.UUID
	var timezone string
	err := r.db.QueryRow(ctx, query, icsToken).Scan(&displayName, &userID, &timezone)
	if err != nil {
		return "", uuid.Nil, "", fmt.Errorf("failed to get feed owner info: %w", err)
	}

	return displayName, userID, timezone, nil
}

// ValidateCalendarOwnership checks that all given calendar IDs belong to the specified user
func (r *UnifiedFeedRepository) ValidateCalendarOwnership(ctx context.Context, userID uuid.UUID, calendarIDs []uuid.UUID) (bool, error) {
	if len(calendarIDs) == 0 {
		return true, nil
	}

	query := `SELECT COUNT(*) FROM calendars WHERE id = ANY($1) AND owner_id = $2`
	var count int
	err := r.db.QueryRow(ctx, query, calendarIDs, userID).Scan(&count)
	if err != nil {
		return false, fmt.Errorf("failed to validate calendar ownership: %w", err)
	}

	return count == len(calendarIDs), nil
}

func (r *UnifiedFeedRepository) getIncludedCalendarIDs(ctx context.Context, feedID uuid.UUID) ([]uuid.UUID, error) {
	query := `SELECT calendar_id FROM unified_feed_calendars WHERE unified_feed_id = $1`

	rows, err := r.db.Query(ctx, query, feedID)
	if err != nil {
		return nil, fmt.Errorf("failed to get included calendar IDs: %w", err)
	}
	defer rows.Close()

	var ids []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, fmt.Errorf("failed to scan calendar ID: %w", err)
		}
		ids = append(ids, id)
	}

	return ids, rows.Err()
}
