// WhenTo - Collaborative event calendar for self-hosted environments
// Copyright (C) 2025 WhenTo Contributors
// SPDX-License-Identifier: BSL-1.1

package repository_test

import (
	"sort"
	"testing"

	"github.com/google/uuid"

	"github.com/whento/whento/internal/ics/repository"
	"github.com/whento/whento/internal/testutil/dbtest"
)

// Skips when DATABASE_URL is unset; see internal/testutil/dbtest.
//
// An ICS token is a bearer credential: whoever holds the URL reads the feed, for ever,
// with no other check. Everything below is about what that token resolves to — which
// calendars, whose name — and about the two operations that bound the exposure:
// regenerating the token and validating that a user may add a calendar at all.

func TestGetCalendarByICSToken(t *testing.T) {
	pool := dbtest.Pool(t)
	repo := repository.NewCalendarRepository(pool)
	ctx := dbtest.Context(t)

	f := seedCalendar(t, pool, "Ada", "Grace", "Katherine")

	cal, err := repo.GetByICSToken(ctx, f.calendar.ICSToken)
	if err != nil {
		t.Fatalf("GetByICSToken: %v", err)
	}

	if cal.ID != f.calendar.ID || cal.Name != "ICS Test" {
		t.Errorf("got %+v, want the seeded calendar", cal)
	}
	if cal.Description != "A calendar to export" {
		t.Errorf("Description = %q", cal.Description)
	}
	if cal.OwnerID != f.owner.ID {
		t.Errorf("OwnerID = %s, want %s", cal.OwnerID, f.owner.ID)
	}
	// The participant count comes from a LEFT JOIN with a GROUP BY. It feeds the
	// "2/3 available" line, so a miscount is visible in every exported event.
	if cal.TotalParticipants != 3 {
		t.Errorf("TotalParticipants = %d, want 3", cal.TotalParticipants)
	}
	if cal.Threshold != 2 || cal.MinDurationHours != 1 || cal.Timezone != "Europe/Paris" {
		t.Errorf("the calendar rules did not survive the scan: %+v", cal)
	}

	if _, err := repo.GetByICSToken(ctx, "no-such-token"); err == nil {
		t.Error("an unknown ICS token returned a calendar")
	}
}

// TestCalendarWithNoParticipantsCountsZero covers the LEFT JOIN. An inner join would drop
// the calendar entirely and the feed would 404 rather than return an empty one.
func TestCalendarWithNoParticipantsCountsZero(t *testing.T) {
	pool := dbtest.Pool(t)
	ctx := dbtest.Context(t)

	f := seedCalendar(t, pool)

	cal, err := repository.NewCalendarRepository(pool).GetByICSToken(ctx, f.calendar.ICSToken)
	if err != nil {
		t.Fatalf("GetByICSToken: %v", err)
	}
	if cal.TotalParticipants != 0 {
		t.Errorf("TotalParticipants = %d, want 0", cal.TotalParticipants)
	}
}

func TestUnifiedFeedCreateAndGet(t *testing.T) {
	pool := dbtest.Pool(t)
	repo := repository.NewUnifiedFeedRepository(pool)
	ctx := dbtest.Context(t)

	f := seedCalendar(t, pool, "Ada")

	if _, _, err := repo.GetByUserID(ctx, f.owner.ID); err == nil {
		t.Error("a user with no feed returned one")
	}

	feed, err := repo.Create(ctx, f.owner.ID)
	if err != nil {
		t.Fatalf("Create: %v", err)
	}
	// The token is generated by a column default rather than in Go. It is the only thing
	// protecting the feed, so an empty or short one would be a real exposure.
	if len(feed.ICSToken) != 64 {
		t.Errorf("ICSToken is %d characters (%q), want the 64 hex characters of 32 bytes",
			len(feed.ICSToken), feed.ICSToken)
	}
	if feed.UserID != f.owner.ID {
		t.Errorf("UserID = %s, want %s", feed.UserID, f.owner.ID)
	}

	// UNIQUE(user_id): a second feed would give one account two live tokens, only one of
	// which the settings page could ever revoke.
	if _, err := repo.Create(ctx, f.owner.ID); err == nil {
		t.Error("a second unified feed was created for the same user")
	}

	got, calendarIDs, err := repo.GetByUserID(ctx, f.owner.ID)
	if err != nil {
		t.Fatalf("GetByUserID: %v", err)
	}
	if got.ID != feed.ID || got.ICSToken != feed.ICSToken {
		t.Errorf("GetByUserID returned %+v, want the feed just created", got)
	}
	if len(calendarIDs) != 0 {
		t.Errorf("a new feed already includes %d calendars", len(calendarIDs))
	}
}

func TestUnifiedFeedCalendarSelection(t *testing.T) {
	pool := dbtest.Pool(t)
	repo := repository.NewUnifiedFeedRepository(pool)
	ctx := dbtest.Context(t)

	first := seedCalendar(t, pool, "Ada", "Grace")
	second := seedCalendar(t, pool, "Katherine")
	// Both calendars belong to the same owner, which is what the feed requires.
	if _, err := pool.Exec(ctx, `UPDATE calendars SET owner_id = $1 WHERE id = $2`,
		first.owner.ID, second.calendar.ID); err != nil {
		t.Fatalf("reassign the second calendar: %v", err)
	}

	feed, err := repo.Create(ctx, first.owner.ID)
	if err != nil {
		t.Fatalf("Create: %v", err)
	}

	if err := repo.UpdateCalendars(ctx, feed.ID, []uuid.UUID{first.calendar.ID, second.calendar.ID}); err != nil {
		t.Fatalf("UpdateCalendars: %v", err)
	}

	_, included, err := repo.GetByUserID(ctx, first.owner.ID)
	if err != nil {
		t.Fatalf("GetByUserID: %v", err)
	}
	if len(included) != 2 {
		t.Fatalf("the feed includes %d calendars, want 2", len(included))
	}

	// UpdateCalendars replaces rather than adds: unticking a calendar in the settings
	// page has to actually remove it from the feed, or a revoked calendar keeps exporting.
	if err := repo.UpdateCalendars(ctx, feed.ID, []uuid.UUID{second.calendar.ID}); err != nil {
		t.Fatalf("UpdateCalendars: %v", err)
	}
	_, included, err = repo.GetByUserID(ctx, first.owner.ID)
	if err != nil {
		t.Fatalf("GetByUserID: %v", err)
	}
	if len(included) != 1 || included[0] != second.calendar.ID {
		t.Errorf("the feed includes %v, want only the second calendar", included)
	}

	// An empty selection clears the feed entirely; the transaction still has to commit.
	if err := repo.UpdateCalendars(ctx, feed.ID, nil); err != nil {
		t.Fatalf("UpdateCalendars with nothing selected: %v", err)
	}
	_, included, err = repo.GetByUserID(ctx, first.owner.ID)
	if err != nil {
		t.Fatalf("GetByUserID: %v", err)
	}
	if len(included) != 0 {
		t.Errorf("the feed still includes %v after being cleared", included)
	}
}

// TestUpdateCalendarsToleratesDuplicates covers the ON CONFLICT DO NOTHING. The same
// calendar named twice must not abort the whole update on the composite primary key.
func TestUpdateCalendarsToleratesDuplicates(t *testing.T) {
	pool := dbtest.Pool(t)
	repo := repository.NewUnifiedFeedRepository(pool)
	ctx := dbtest.Context(t)

	f := seedCalendar(t, pool, "Ada")
	feed, err := repo.Create(ctx, f.owner.ID)
	if err != nil {
		t.Fatalf("Create: %v", err)
	}

	if err := repo.UpdateCalendars(ctx, feed.ID, []uuid.UUID{f.calendar.ID, f.calendar.ID}); err != nil {
		t.Fatalf("UpdateCalendars with a duplicate: %v", err)
	}

	_, included, err := repo.GetByUserID(ctx, f.owner.ID)
	if err != nil {
		t.Fatalf("GetByUserID: %v", err)
	}
	if len(included) != 1 {
		t.Errorf("the feed includes %d rows, want the calendar once", len(included))
	}
}

func TestGetCalendarsForFeedAndOwnerInfo(t *testing.T) {
	pool := dbtest.Pool(t)
	repo := repository.NewUnifiedFeedRepository(pool)
	ctx := dbtest.Context(t)

	f := seedCalendar(t, pool, "Ada", "Grace")
	feed, err := repo.Create(ctx, f.owner.ID)
	if err != nil {
		t.Fatalf("Create: %v", err)
	}
	if err := repo.UpdateCalendars(ctx, feed.ID, []uuid.UUID{f.calendar.ID}); err != nil {
		t.Fatalf("UpdateCalendars: %v", err)
	}

	calendars, err := repo.GetCalendarsForFeed(ctx, feed.ICSToken)
	if err != nil {
		t.Fatalf("GetCalendarsForFeed: %v", err)
	}
	if len(calendars) != 1 {
		t.Fatalf("got %d calendars, want 1", len(calendars))
	}
	if calendars[0].ID != f.calendar.ID || calendars[0].TotalParticipants != 2 {
		t.Errorf("got %+v, want the seeded calendar with two participants", calendars[0])
	}

	// An unknown token resolves to nothing rather than to everything, which is the
	// failure mode that would turn a typo into a full disclosure.
	none, err := repo.GetCalendarsForFeed(ctx, "no-such-token")
	if err != nil {
		t.Fatalf("GetCalendarsForFeed with an unknown token: %v", err)
	}
	if len(none) != 0 {
		t.Errorf("an unknown token returned %d calendars", len(none))
	}

	name, userID, timezone, err := repo.GetFeedOwnerInfo(ctx, feed.ICSToken)
	if err != nil {
		t.Fatalf("GetFeedOwnerInfo: %v", err)
	}
	// The timezone is what the ICS writer converts every event into; the wrong one shifts
	// the whole feed by hours.
	if name != "Ada Lovelace" || userID != f.owner.ID || timezone != "Europe/Paris" {
		t.Errorf("owner info = %q/%s/%q, want Ada Lovelace in Europe/Paris", name, userID, timezone)
	}

	if _, _, _, err := repo.GetFeedOwnerInfo(ctx, "no-such-token"); err == nil {
		t.Error("an unknown token returned owner information")
	}
}

// TestRegenerateToken is the revocation path: the old URL must stop working the moment a
// new token is issued, or sharing a feed by mistake could never be undone.
func TestRegenerateToken(t *testing.T) {
	pool := dbtest.Pool(t)
	repo := repository.NewUnifiedFeedRepository(pool)
	ctx := dbtest.Context(t)

	f := seedCalendar(t, pool, "Ada")
	feed, err := repo.Create(ctx, f.owner.ID)
	if err != nil {
		t.Fatalf("Create: %v", err)
	}
	if err := repo.UpdateCalendars(ctx, feed.ID, []uuid.UUID{f.calendar.ID}); err != nil {
		t.Fatalf("UpdateCalendars: %v", err)
	}

	fresh, err := repo.RegenerateToken(ctx, feed.ID)
	if err != nil {
		t.Fatalf("RegenerateToken: %v", err)
	}
	if fresh == feed.ICSToken {
		t.Fatal("the token did not change")
	}
	if len(fresh) != 64 {
		t.Errorf("the new token is %d characters, want 64", len(fresh))
	}

	old, err := repo.GetCalendarsForFeed(ctx, feed.ICSToken)
	if err != nil {
		t.Fatalf("GetCalendarsForFeed with the old token: %v", err)
	}
	if len(old) != 0 {
		t.Error("the old token still resolves to the feed's calendars")
	}

	// The selection survives the rotation; only the URL changes.
	current, err := repo.GetCalendarsForFeed(ctx, fresh)
	if err != nil {
		t.Fatalf("GetCalendarsForFeed with the new token: %v", err)
	}
	if len(current) != 1 {
		t.Errorf("the new token resolves to %d calendars, want 1", len(current))
	}

	if _, err := repo.RegenerateToken(ctx, uuid.New()); err == nil {
		t.Error("regenerating the token of an unknown feed reported success")
	}
}

// TestValidateCalendarOwnership is the authorisation check on the way in: without it a
// user could add somebody else's calendar to their own feed and read it for ever.
func TestValidateCalendarOwnership(t *testing.T) {
	pool := dbtest.Pool(t)
	repo := repository.NewUnifiedFeedRepository(pool)
	ctx := dbtest.Context(t)

	mine := seedCalendar(t, pool, "Ada")
	alsoMine := seedCalendar(t, pool, "Grace")
	if _, err := pool.Exec(ctx, `UPDATE calendars SET owner_id = $1 WHERE id = $2`,
		mine.owner.ID, alsoMine.calendar.ID); err != nil {
		t.Fatalf("reassign: %v", err)
	}
	theirs := seedCalendar(t, pool, "Alan")

	tests := []struct {
		name      string
		calendars []uuid.UUID
		want      bool
	}{
		{"nothing selected", nil, true},
		{"one of mine", []uuid.UUID{mine.calendar.ID}, true},
		{"both of mine", []uuid.UUID{mine.calendar.ID, alsoMine.calendar.ID}, true},
		{"somebody else's", []uuid.UUID{theirs.calendar.ID}, false},
		// The check counts matches, so one foreign calendar hidden among mine has to
		// fail the whole request rather than be silently dropped.
		{"mine plus one of theirs", []uuid.UUID{mine.calendar.ID, theirs.calendar.ID}, false},
		{"a calendar that does not exist", []uuid.UUID{uuid.New()}, false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ok, err := repo.ValidateCalendarOwnership(ctx, mine.owner.ID, tt.calendars)
			if err != nil {
				t.Fatalf("ValidateCalendarOwnership: %v", err)
			}
			if ok != tt.want {
				t.Errorf("got %v, want %v", ok, tt.want)
			}
		})
	}
}

// TestDeletingACalendarRemovesItFromFeeds covers the cascade. A dangling row would make
// the feed query fail its join or, worse, resolve to whatever calendar next took the id.
func TestDeletingACalendarRemovesItFromFeeds(t *testing.T) {
	pool := dbtest.Pool(t)
	repo := repository.NewUnifiedFeedRepository(pool)
	ctx := dbtest.Context(t)

	f := seedCalendar(t, pool, "Ada")
	other := seedCalendar(t, pool, "Grace")
	if _, err := pool.Exec(ctx, `UPDATE calendars SET owner_id = $1 WHERE id = $2`,
		f.owner.ID, other.calendar.ID); err != nil {
		t.Fatalf("reassign: %v", err)
	}

	feed, err := repo.Create(ctx, f.owner.ID)
	if err != nil {
		t.Fatalf("Create: %v", err)
	}
	if err := repo.UpdateCalendars(ctx, feed.ID, []uuid.UUID{f.calendar.ID, other.calendar.ID}); err != nil {
		t.Fatalf("UpdateCalendars: %v", err)
	}

	if _, err := pool.Exec(ctx, `DELETE FROM calendars WHERE id = $1`, other.calendar.ID); err != nil {
		t.Fatalf("delete calendar: %v", err)
	}

	_, included, err := repo.GetByUserID(ctx, f.owner.ID)
	if err != nil {
		t.Fatalf("GetByUserID: %v", err)
	}
	sort.Slice(included, func(i, j int) bool { return included[i].String() < included[j].String() })
	if len(included) != 1 || included[0] != f.calendar.ID {
		t.Errorf("the feed includes %v, want only the surviving calendar", included)
	}
}
